### PR TITLE
converted es6 syntax to es5

### PR DESCRIPTION
**Pull request by sylhero**
I just found there are two more places that need to be fixed

### CODE REVIEW

**Comment by shirohana** [comment]
Hello,
Could you add spaces between parentheses? I didn't specified a linter file.

By the way, why do you adhere to use ES5 only with webpack? Is ES6/ES7 not awesome enough?

**Comment by sylhero** [comment]
https://www.npmjs.com/package/uglifyjs-webpack-plugin
`Important! The plugin has a peer dependency to uglify-js, so in order to use the plugin, also uglify-js has to be installed. The currently (2017/1/25) available uglify-js npm packages; however, do not support minification of ES6 code. In order to support ES6, an ES6-capable, a.k.a. harmony, version of UglifyJS has to be provided.`
based on that, I think it's better to stay with es5 so whoever uses your module wouldn't need extra configuration.

**Comment by shirohana** [comment]
Seems good, thank you for contribution :)

I'll squash these two commits and merge.

**Comment by sylhero** [comment]
no problem! BTW, can u merge it and publish to npm?

**Comment by shirohana** [comment]
Yah, as soon as possible :)

**Comment by shirohana** [comment]
Published :)

**Pull request merged**
